<?php

$mockArray = [];



$bookNames = array(
    "Sands of Time",
    "Inferno's Echo",
    "Veil of Midnight",
    "The Crystal Shard",
    "Ocean's Tears",
    "The Darkened Spire",
    "Invisible Chains",
    "Phantom's Requiem",
    "Ravens of the Abyss",
    "Starfall",
    "Rising Phoenix",
    "Storm of Vengeance",
    "Fire and Ash",
    "The Alabaster Throne",
    "Illusions of Grandeur",
    "Titan's Grasp",
    "Winter's Embrace",
    "Wings of the Night",
    "Eternal Shadow",
    "Legacy of Ruin",
    "Harbingers of Doom",
    "Riddles of the Sphinx",
    "Cosmic Entropy",
    "Oracle's Lament",
    "The Dragon's Roost",
    "Cursed Waters",
    "Chronicles of Despair",
    "Lunar Legacy",
    "Blaze of Glory",
    "The Immortal Coil",
    "Waves of Destiny",
    "The Eternal Maze",
    "Chasing Illusions",
    "Twilight's Fall",
    "The Ghost Ship",
    "The Eternal Flame",
    "The Iron Fist",
    "Eclipsing Worlds",
    "The Forgotten City",
    "Rune of the Fallen",
    "The Serpent's Tongue",
    "Infernal Abyss",
    "The Crystal Cavern",
    "Beyond Reality",
    "Quest for the Lost",
    "Guardians of the Void",
    "Storm's Descent",
    "Revelations of the Deep",
    "Witch's Hex",
    "Haunting Melodies",
    "The Lost Arcanum",
    "Heart of Chaos",
    "The Frozen Wasteland",
    "The Scorched Earth",
    "Fallen Kingdoms",
    "Eclipse of the Sun",
    "Blood and Honor",
    "The Demon's Eye",
    "Sacred Scrolls",
    "Vortex of Chaos",
    "Wanderer's Oath",
    "Spectral Realm",
    "Celestial Odyssey",
    "Starlit Night",
    "Pathways to Eternity",
    "The Iron Citadel",
    "Lost in the Abyss",
    "Time's Crucible",
    "Shattered Dreams",
    "Whispers in the Wind",
    "Darkened Souls",
    "Chronicles of the Lost",
    "The Devil's Tears",
    "Awakening the Beast",
    "Maze of Nightmares",
    "Harbor of Echoes",
    "Path of the Ancestors",
    "Worlds Beyond",
    "Guardians of Light",
    "The Demon's Chains",
    "The Silvered Path",
    "Dark Reflections",
    "Mysteries of the Deep",
    "The Iron Rose",
    "The Last Oracle",
    "Frozen Depths",
    "Kingdom of the Forsaken",
    "The Cursed Jewel",
    "Eclipsing Twilight",
    "Mortal Desires",
    "Eternal Whispers",
    "The Shadowed Path",
    "The Bloodied Sword",
    "Chronicles of the Wind",
    "The Sunken City",
    "Storm's Fury",
    "Twilight of the Gods",
    "The Celestial Key",
    "Awakening the Shadows",
    "Tales of the Brave",
    "The Eldritch Maze",
    "Eternal Frost",
    "The Enchanted Isle",
    "The Withered Rose",
    "Crimson Sky",
    "The Titan's Fall",
    "Shores of Eternity",
    "Destiny's Knot",
    "Winds of Change",
    "Chains of Frost",
    "Sorcerer's Vendetta",
    "Eclipsed Moon",
    "The Devil's Throne",
    "The Emerald Isle",
    "The Infinite Quest",
    "Dreams of the Forsaken",
    "Voyage Beyond",
    "The Serpent's Wake",
    "The Lost Horizon",
    "Oracle's Vision",
    "The Enchanted Forest",
    "Storm's Wake",
    "The Silvered Mirror",
    "Tales of the Damned",
    "The Crimson Sea",
    "Fallen Grace",
    "The Dragon's Tear",
    "The Broken Shield",
    "The Eternal Void",
    "Awakening the Serpent",
    "Riddles of Destiny",
    "Starlit Dreams",
    "Chains of the Abyss",
    "Quest for the Grail",
    "Infernal Temptation",
    "Whispers of the Damned",
    "The Celestial War",
    "The Dragon's Nest",
    "The Phoenix's Ashes",
    "Frozen Tundra",
    "The Shattered Mirror",
    "Burning Skies",
    "Celestial Equinox",
    "Destiny's Embrace",
    "The Forsaken Land",
    "The Haunted Keep",
    "The Enchanted Blade",
    "Chronicles of the Moon",
    "Rune of the Damned",
    "The Shattered Realm",
    "Heaven's Gate",
    "The Cursed Flame",
    "Gates of Destiny",
    "The Devil's Game",
    "Fallen Empires",
    "The Iron Heart",
    "The Eternal Fountain",
    "Echoes of Eternity",
    "The Devil's Maze",
    "The Cosmic Rift",
    "Awakened Light",
    "Tales of the Phoenix",
    "The Infinite Abyss",
    "Lost in Eternity",
    "Serpent's Lair",
    "Destiny's Web",
    "The Forgotten Isle",
    "Eclipsed Dawn",
    "Chronicles of the Earth",
    "The Cursed Sanctuary",
    "The Iron Helm",
    "The Celestial Scroll",
    "Winds of the Abyss",
    "Whispers of the Void",
    "Infernal Flames",
    "The Serpent's Lair",
    "The Eternal Well",
    "Voyage to the Unknown",
    "Tales of the Forgotten",
    "The Lost Odyssey",
    "Sorcerer's Bane",
    "Chronicles of the Star",
    "Wanderer's Curse",
    "Cursed Lands",
    "The Phoenix's Nest",
    "The Celestial Tower",
    "The Broken Seal",
    "Shattered Illusions",
    "The Iron Mask",
    "The Eternal Labyrinth",
    "Destiny's Maze",
    "Lost in Time",
    "The Shattered Crown",
    "The Lost Fortress",
    "The Eternal Garden",
    "Infernal Desires",
    "The Broken Spear",
    "Twilight's Embrace"
);


function randAut()
{
    $bookAuthors = array(
        "Alice Tremaine",
        "Benjamin Holloway",
        "Cassandra Williams",
        "David Elmsworth",
        "Emily Watson",
        "Franklin O'Hara",
        "Grace Caldwell",
        "Henry Simmons",
        "Isabella Fincher",
        "Joseph Thornton",
        "Katherine DuPont",
        "Lucas Montgomery",
        "Molly O'Connell",
        "Nigel Armstrong",
        "Olivia Sanders",
        "Patrick Kingsley",
        "Quinn Harper",
        "Rebecca Sterling",
        "Samuel Blackwood",
        "Teresa Reynolds",
        "Ulysses Grant",
        "Victoria White",
        "Walter Fitzroy",
        "Xander Norton",
        "Yvonne Bradley",
        "Zachary Mitchell",
        "Anne Greene",
        "Bradley Quinn",
        "Clara Wilson",
        "Derek Summers",
        "Eleanor Price",
        "Frederick Vaughn",
        "Gloria Patterson",
        "Harrison Wright",
        "Isaac Stone",
        "Julia Loomis",
        "Kenneth Hayes",
        "Laura Clarke",
        "Mark Owens",
        "Nancy Delaney",
        "Oscar Wells",
        "Paula Foster",
        "Quincy Mills",
        "Reed Langley",
        "Samantha Brown",
        "Theodore Grant",
        "Ursula Moore",
        "Valerie Mason",
        "William Harrison",
        "Xenia Walsh"
    );

    $j = count($bookAuthors) - 1;
    return $bookAuthors[rand(0, $j)];
};



function randColor()
{
    $color = array("red", "blue", "green", "yellow", "purple", "pink", "orange", "brown", "black");
    $j = count($color) - 1;
    return $color[rand(0, $j)];
}



for ($i = 0; $i < 200; $i++) {
    $book = $bookNames[$i];

    $mockArray[$book]['title'] = $book;
    $mockArray[$book]['color'] = randColor();
    $mockArray[$book]['author'] = randAut();
    $mockArray[$book]['pages'] = rand(400, 2000);
    $mockArray[$book]['release'] = rand(1899, 2023);
}


echo "<pre>";
var_export($mockArray);
echo "</pre>";
