<?php

$mockArray = [];



$bookNames = array(
    "Mystical Journey",
    "Shadows of Tomorrow",
    "Echoes of the Past",
    "Whispers in the Dark",
    "Secrets Unveiled",
    "Dance of Destiny",
    "Twilight's Embrace",
    "Beneath the Sky",
    "Realm of Dreams",
    "Lost Horizons",
    "Sirens' Call",
    "Echoes of the Past2",
    "Whispers in the Dark2",
    "Guardians of Fate",
    "Veil of Midnight",
    "Forgotten Realms",
    "Quest for Honor",
    "Chasing Echoes",
    "Silent Oaths",
    "Rising Phoenix",
    "Frozen Hearts",
    "Moonlit Nights",
    "Stars Above, Earth Below",
    "Whispers of War",
    "Eternal Enigma",
    "Tides of Time",
    "Winds of Change",
    "Fire's Fury",
    "Water's Whimsy",
    "Earthen Embrace",
    "Air's Ascent",
    "Shattered Dreams",
    "Glimmering Hope",
    "Lost and Found",
    "Destiny's Door",
    "Tales of Triumph",
    "Mysteries Unfolded",
    "Chapters of Chaos",
    "Battles Unseen",
    "Quest of the Quill",
    "Realm's Reverie",
    "Palace of Peril",
    "Fortress of Fate",
    "Mansion of Mysteries",
    "Garden of Gloom",
    "Desert's Despair",
    "Oasis of Optimism",
    "Forest of Fables",
    "Mountain's Majesty",
    "Canyon's Cry",
    "Rivers of Regret",
    "Seas of Serendipity",
    "Lakes of Longing",
    "Ponds of Perfection",
    "Sands of Solitude",
    "Rocks of Resilience",
    "Meadows of Melancholy",
    "Hills of Hope",
    "Valleys of Valor",
    "Caves of Curiosity",
    "Beaches of Bliss",
    "Islands of Illusion",
    "Oceans of Opportunity",
    "Tundras of Turmoil",
    "Glaciers of Grace",
    "Swamps of Secrets",
    "Prairies of Promise",
    "Lands of Legend",
    "Fields of Fortune",
    "Dunes of Desolation",
    "Plains of Perseverance",
    "Moors of Mystery",
    "Harbors of Harmony",
    "Bays of Bravery",
    "Coasts of Curiosity",
    "Strands of Strategy",
    "Ridges of Risk",
    "Ledges of Luck",
    "Cliffs of Challenge",
    "Plateaus of Potential",
    "Volcanoes of Victory",
    "Watersheds of Wisdom",
    "Gulfs of Greatness",
    "Peninsulas of Potential",
    "Reefs of Resilience",
    "Channels of Change",
    "Lagoons of Legacy",
    "Streams of Strategy",
    "Brooks of Bravery",
    "Fjords of Fortune",
    "Creeks of Creativity",
    "Rapids of Resolve",
    "Waterfalls of Wisdom",
    "Springs of Success",
    "Deltas of Dedication",
    "Estuaries of Excellence",
    "Reservoirs of Resolve",
    "Lakesides of Legacy",
    "Pools of Prosperity",
    "Marshes of Mastery",
    "Bogs of Boldness",
    "Wetlands of Wonder",
    "Rainforests of Radiance",
    "Jungles of Joy",
    "Groves of Growth",
    "Orchards of Opportunity",
    "Vines of Victory",
    "Bushes of Beauty",
    "Shrubs of Strength",
    "Savannas of Success",
    "Grasslands of Greatness",
    "Steppes of Strategy",
    "Tundras of Triumph",
    "Icelands of Imagination",
    "Deserts of Determination",
    "Badlands of Bravery",
    "Dunes of Dedication",
    "Barrens of Beauty",
    "Wilds of Wisdom",
    "Wilderness of Willpower",
    "Outbacks of Optimism",
    "Pampas of Potential",
    "Prairies of Prosperity",
    "Fields of Fulfillment",
    "Meadows of Mastery",
    "Pastures of Perseverance",
    "Terrains of Triumph",
    "Lands of Lore",
    "Regions of Radiance",
    "Zones of Zeal",
    "Areas of Ambition",
    "Iter Mysticum",
    "Umbrae Crastini",
    "Voces Praeteriti",
    "Susurri Tenebris",
    "Arcana Revelata",
    "Chorea Fatum",
    "Amplexus Crepusculi",
    "Sub Caelo",
    "Regnum Somniorum",
    "Horizontes Perditi",
    "Vocatio Sirenarum",
    "Custodes Fortunae",
    "Velum Mediae Noctis",
    "Regna Oblivionis",
    "Quaestus Honorem",
    "Echos Repercussus",
    "Sacramenta Silenti",
    "Phoenix Ascendens",
    "Cordis Glaciei",
    "Noctes Luna Splendens",
    "Stellae Super Terra",
    "Bella Susurrus",
    "Aeternum Sphinx",
    "Mare Temporis",
    "Ventorum Mutatio",
    "Ira Ignis",
    "Ludus Aquarum",
    "Terra Amplexus",
    "Ascensus Aeris",
    "Somnia Fracta",
    "Spes Micans",
    "Perditus et Inventum",
    "Porta Destini",
    "Victoriae Narratio",
    "Mysteria Explicata",
    "Chaos Libellorum",
    "Pugnae Absconditae",
    "Calamus Questus",
    "Visio Regni",
    "Periculum Palatii",
    "Fatum Arcis",
    "Mysteria Domus",
    "Hortus Maestitiae",
    "Desertum Desperationis",
    "Optimismi Oasis",
    "Fabulae Silvae",
    "Mons Maiestatis",
    "Clamor Convalis",
    "Flumina Flebilis",
    "Mara Serendipitatis",
    "Lacus Desiderii",
    "Stagna Perfectio",
    "Solitudinis Arenae",
    "Petrae Resilientiae",
    "Prata Melancholiae",
    "Collis Spei",
    "Vallium Virtutis",
    "Curiositas Cavernarum",
    "Beatitudinis Litora",
    "Insulae Illusionis",
    "Opportunitatis Oceani",
    "Turbatio Tundrarum",
    "Gratia Glaciarum",
    "Arcana Paludum",
    "Promissum Praeriarum",
    "Legenda Terrarum",
    "Fortuna Camporum",
    "Solitudinis Dunes",
    "Patientia Planities",
    "Mysterium Moor",
    "Concordia Portuum",
    "Sinus Fortitudinis",
    "Curiositas Litorum",
    "Strategiae Striae",
    "Risus Cretarum",
    "Fortuna Margines",
    "Proclivium Proelium",
    "Potentialis Platea",
    "Victoriae Volcani",
    "Sapientiae Divortium",
    "Magnitudo Sinus",
    "Potentialis Peninsulas",
    "Resilientiae Recifes",
    "Mutationis Canales",
    "Legatum Lagoons",
    "Strategiae Rivi",
    "Fortitudinis Rivi",
    "Fortuna Fjords",
    "Creativitas Creek",
    "Solutio Rapidae",
    "Sapientiae Cataractae",
    "Successus Springs",
    "Dedicationis Deltas",
    "Praestantiae Estuaria",
    "Solutio Reservorum",
    "Hereditatis Litoris",
    "Prosperitatis Piscinae",
    "Magisterii Marshes",
    "Boldness Paludes",
    "Miraculum Palustris",
    "Radiantia Pluviae Silvae",
    "Gaudium Jungles",
    "Crescentis Luci",
    "Opportunitatis Pomaria",
    "Victoriae Vites",
    "Pulchritudinis Frutices",
    "Roboris Dumos",
    "Successus Savannas",
    "Magnitudo Pratensium",
    "Strategiae Steppes",
    "Triumphus Tundras",
    "Imaginis Glacies",
    "Determinationis Desertis",
    "Audaciae Dunes",
    "Dedicationis Arida",
    "Pulchritudinis Barrens",
    "Sapientiae Wilds",
    "Voluntas Deserti",
    "Optimismi Outbacks",
    "Potentialis Pampas",
    "Prosperitatis Praeriarum",
    "Satisfactionis Campis",
    "Magisterii Pratis",
    "Perseverantiae Pastores",
    "Triumphus Terrae",
    "Lore Terrarum",
    "Radiantia Regionum",
    "Zelus Zonae",
    "Ambitionis Areas"
);


function randAut()
{
    $bookAuthors = array(
        "Alice Tremaine",
        "Benjamin Holloway",
        "Cassandra Williams",
        "David Elmsworth",
        "Emily Watson",
        "Franklin O'Hara",
        "Grace Caldwell",
        "Henry Simmons",
        "Isabella Fincher",
        "Joseph Thornton",
        "Katherine DuPont",
        "Lucas Montgomery",
        "Molly O'Connell",
        "Nigel Armstrong",
        "Olivia Sanders",
        "Patrick Kingsley",
        "Quinn Harper",
        "Rebecca Sterling",
        "Samuel Blackwood",
        "Teresa Reynolds",
        "Ulysses Grant",
        "Victoria White",
        "Walter Fitzroy",
        "Xander Norton",
        "Yvonne Bradley",
        "Zachary Mitchell",
        "Anne Greene",
        "Bradley Quinn",
        "Clara Wilson",
        "Derek Summers",
        "Eleanor Price",
        "Frederick Vaughn",
        "Gloria Patterson",
        "Harrison Wright",
        "Isaac Stone",
        "Julia Loomis",
        "Kenneth Hayes",
        "Laura Clarke",
        "Mark Owens",
        "Nancy Delaney",
        "Oscar Wells",
        "Paula Foster",
        "Quincy Mills",
        "Reed Langley",
        "Samantha Brown",
        "Theodore Grant",
        "Ursula Moore",
        "Valerie Mason",
        "William Harrison",
        "Xenia Walsh"
    );

    $j = count($bookAuthors) - 1;
    return $bookAuthors[rand(0, $j)];
};



function randColor()
{
    $color = array("#493638", "#A48765", "#FFD791", "#DA5552", "#DF7373", "#E39695", "#E4B1AB");
    $j = count($color) - 1;
    return $color[rand(0, $j)];
}



for ($i = 0; $i < 259; $i++) {
    $book = $bookNames[$i];

    $mockArray[$book]['title'] = $book;
    $mockArray[$book]['color'] = randColor();
    $mockArray[$book]['author'] = randAut();
    $mockArray[$book]['pages'] = rand(400, 2000);
    $mockArray[$book]['release'] = rand(1899, 2023);
}


echo "<pre>";
var_export($mockArray);
echo "</pre>";
